#! /bin/sh

set -ex

squid_pidfile=/var/run/squid/squid.pid
db_dir=/var/lib/squidguard/db
blacklists_url=ftp://ftp.ut-capitole.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz

if [ "x$1" = "x--boot" ]; then
  use_cached_blacklist=true
else
  use_cached_blacklist=false
fi

cd $db_dir
if [ -d blacklists ] && $use_cached_blacklist; then
  : Use cached blacklists
else
  rm -f blacklists.tar.gz
  curl -o blacklists.tar.gz $blacklists_url
  tar xvf blacklists.tar.gz
  squidGuard -C all
fi

if [ -f $squid_pidfile ]; then
  kill -HUP $(cat $squid_pidfile)
fi
